[[instances]]
    progs = "/home/mamh/work/github/go-mtail/test" # prog dir1
    logs = ["/home/mamh/work/github/go-mtail/test/kern.log"]
    override_timezone = "Asia/Shanghai"
    emit_metric_timestamp = "true" #string type

