# # collect interval
# interval = 15

[[instances]]
## List of repositories to monitor.
#repositories = [
#    "flashcatcloud/categraf",
#    "flashcatcloud/nightingale",
#    "flashcatcloud/n9e-helm"
#]

## Github API access token.  Unauthenticated requests are limited to 60 per hour.
# access_token = ""

## Github API enterprise url. Github Enterprise accounts must specify their base url.
# enterprise_base_url = ""

## Timeout for HTTP requests.
# http_timeout = "5s"

## List of additional fields to query.
## NOTE: Getting those fields might involve issuing additional API-calls, so please
##       make sure you do not exceed the rate-limit of GitHub.
##
## Available fields are:
## 	- pull-requests			-- number of open and closed pull requests (2 API-calls per repository)
# additional_fields = []

#[[instances]]

#repositories = [
#    "golang108/influxdata_telegraf",
#    "golang108/flashcatcloud-categraf",
#]
#
#access_token = ""
#
